### ISSUE TITLE
guh config gone after update

### ISSUE THREAD

**Issue by Boernsman** [guh/guh#120] opened 2015-02-20 19:21 UTC
guh config is gone everytime after i update my guh system.
guhd (0.2.0+201502201635~77decc2~trusty) 

Update with apt-get update -> upgrade

started the guhd server with following command: service guhd start

**Comment by t-mon** [comment] 2015-02-21 09:45
which config? the logs, the devices or the rules?
are the files still there?
*  `~/.config/guh/devices.conf`
* or if you start as daemon (`/.config/guh/devices.conf)
* or the log file `/tmp/guhd-logs.sqlite`

**Comment by Boernsman** [comment] 2015-02-21 12:04
All devices will be gone, even when i just restart guhd - 'service guhd restart'
After restarting the guhd sever severel times, i deleted the config files. guhd doesn't generate a new - added also new devices again - after restarting the server all the devices i've added are removed. I tried this this on trusty and utopic

**Comment by t-mon** [comment] 2015-02-21 12:07
this bug will be fixed with #93.

**Comment by t-mon** [comment] 2015-02-24 09:03
i cannot reproduce this bug. you have to be root to see where the configs are. This issue is no longer relevant with the new init script ( #122) . 
If you still have this problem, reopen the issue.

**Closed by t-mon** 2015-02-24 09:03 UTC
Labels: bug
